<?xml version="1.0" encoding="utf-8"?><Database Name="ShoeShop" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-8JPNURT;Initial Catalog=ShoeShop;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ShoesShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="account_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="avatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="role_code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="role_code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="role_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Brand" Member="Brands">
    <Type Name="Brand">
      <Column Name="brand_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="brand_code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="brand_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category_code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="category_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="comment_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="account_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Member="comment1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="star" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Discount" Member="Discounts">
    <Type Name="Discount">
      <Column Name="discount_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="discount_code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="discount_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="account_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="order_item" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="type_payment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="brand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="origin" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="size" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductColor" Member="ProductColors">
    <Type Name="ProductColor">
      <Column Name="product_color_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="color" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductDetail" Member="ProductDetails">
    <Type Name="ProductDetail">
      <Column Name="product_detail_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="detail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductImage" Member="ProductImages">
    <Type Name="ProductImage">
      <Column Name="product_image_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Blog" Member="Blogs">
    <Type Name="Blog">
      <Column Name="blog_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="descrip" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="content_html" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>